### ISSUE TITLE
Scrambling length-1 puzzles locks up the program.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cutelyaware/magiccube4d#102]
```
What can I say? I had to go for some first solutions! :)

The while loop at MC4DSwing.java line 496 is to blame - it goes infinite.

Scrambling any number of moves will do this.
```

Original issue reported on code.google.com by `roi...@gmail.com` on 2 Dec 2009 at 7:14

**Comment by SharkRetriever** [comment]
Hi
For size one puzzles, should the choice to scramble just be disabled?

**Comment by cutelyaware** [comment]
Perhaps.

**Comment by SharkRetriever** [comment]
Implemented in local version on my computer. Looks like this: http://prntscr.com/7utp12
Shortcuts are by default disabled along with those menu items so no way of scrambling.

In terms of user friendliness might want to have the option enabled instead but then have MessageBox pop up telling them "You can't really scramble a size 1 puzzle" when they try?

**Comment by cutelyaware** [comment]
From a usability perspective, the warning dialog is better because it is clear whereas users often will not know why a menu item is disabled. I would not do either of these things because each is special-case code that must be maintained, and that cost and distraction every time someone looks at that code must be weighed against the benefit which is so small that it is not worth worrying about. Of course any infinite loop is important enough to deserve some attention, even in such a rare situation, so I would look for a simple way to avoid that, hopefully without even testing for this special situation. The behavior would then be identical to a scramble of any puzzle: User wants it scrambled? OK, it's done! :-)

**Comment by SharkRetriever** [comment]
"The behavior would then be identical to a scramble of any puzzle" 
Not quite sure how to implement this, but this hack added to MC4DSwing.java on line 545 will fake it; now the user will be informed that "X random twists" have been made or even "fully scrambled", but the puzzle won't change at all -- not even in viewpoint. A blank scramble will be written to the log file.
if (puzzleManager.puzzleDescription.getEdgeLength() != 1) {
	                for(int s = 0; s < scrambleTwists; s++) {

**Comment by cutelyaware** [comment]
OK, I'm probably wrong about that. It's been a long time since I looked 
at that code. Are you sure a blank scramble will be written? They might 
be reasonable scramble twists but of course none of them will do 
anything. I'm sure there's an elegant solution there somewhere that 
doesn't involve any special case code. It's definitely worth my time 
(I'd much rather make the stereo support solid), but it definitely 
sounds like a nice coding puzzle for you. Here's my super-secret formula 
for coding breakthrough success: 1) Get real familiar with the code and 
try out a bunch or experiments. Then 2) go to sleep. Finally, 3) go back 
to working on it first thing once you're really awake. I bet you'll have 
some sort of important thought within the first 5 minutes. It has 
*always* worked for me.

**Comment by SharkRetriever** [comment]
Yeah I've used that method of sleeping before.
The thing about size 1 puzzles is that twists aren't even allowed; only entire rotations are. For example, I tried moving that if statement to inside the while true loop to avoid an infinite loop and this happened:
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: applyTwistToState called on gripIndex 161 which does not rotate!

Maybe scrambles for size 1 should be rotations?
However, it does seem a little strange that highlight by cubie highlights the entire puzzle when 
Ctrl + click is used.

**Comment by cutelyaware** [comment]
On 7/21/2015 7:17 AM, Ray Z wrote:
>
> Yeah I've used that method of sleeping before.
> The thing about size 1 puzzles is that twists aren't even allowed; 
> only entire rotations are. For example, I tried moving that if 
> statement to inside the while true loop to avoid an infinite loop and 
> this happened:
> Exception in thread "AWT-EventQueue-0" 
> java.lang.IllegalArgumentException: applyTwistToState called on 
> gripIndex 161 which does not rotate!
>

Well the first thing I'd do is to understand why it's throwing that 
exception. Would it cause a problem to not throw that exception or is it 
due to someone being perhaps overly  cautious about demanding sane 
input? If nothing else, try commenting out that statement and see what 
happens.

> Maybe scrambles for size 1 should be rotations?
>

That would be one way to maybe sneak them past whatever code is throwing 
the exception, but remember that an ideal solution would not test for 
this special case anywhere.

> However, it does seem a little strange that highlight by cubie 
> highlights the entire puzzle when
> Ctrl + click is used.
>

Is there no limit to how small of a problem will bother you? :-) That 
will exasperate a lot of people but it's also strong evidence that you 
have the right personality type for the work. It's also evidence that 
you're a junior programmer, but you should grow out of that.

In this case it's clearly a bug, though maybe I should call it a 
microbe! Go chase this one down too if it bothers you enough, but again, 
look first for solutions that do not require checking for special cases. 
When the seriousness of a bug is high enough, adding special case tests 
is fine, and sometimes they're worth doing to truly horrible things, but 
if I were going to perform a code review on a bug fix for something this 
minor, I'd insist that it be simple and more general than previous 
rather than even slightly less. I hope that helps.

**Comment by cutelyaware** [comment]
In the end I decided to add a special case after all. Thanks for all the thoughts.
