### ISSUE TITLE
Cheats don't always finish properly.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cutelyaware/magiccube4d#42]
```
Canceled cheats don't finish properly when restarted.
```

Original issue reported on code.google.com by `roi...@gmail.com` on 19 Oct 2009 at 12:43

**Comment by cutelyaware** [comment]
Fixed in v4.1 commit 88ecfb6f5be914645ddea979d1b20bc022b1cc47 where the scramble boundary mark was not being deleted. In the latest version the first thing that happens in an automated solve is that *all* marks are stripped. That involves a loss of a fair bit of information but the user did ask for it.
