### ISSUE TITLE
Tetrahedral prism not working.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cutelyaware/magiccube4d#5]
```
We should definitely have all the prisms based on platonic solids working.  
The following puzzles result in not-implemented exceptions:

{3,3}x{} 3
{3,4}x{} 3
{3,5}x{} 3


```

Original issue reported on code.google.com by `roi...@gmail.com` on 30 Jul 2009 at 5:02

**Comment by donhatch** [comment]
Seems to be working now: 
- Roice's 6a03fbe1762161fd5165018acd114364696aed19 on 2009/11/11 gave a workaround that made it work, I think, but didn't enable it in the menu due to "twisting limitations with this puzzle due to r156" according to the commit message; I'm not sure whether that's still an issue or not.  (This puzzle does indeed have twisting limitations making it not very usable when edge length is small like 2 or even 3, but that's not unique to this puzzle; small edge lengths should perhaps be removed from most of the puzzles)
- my 4d6359971d5df93da60c8553bd88e5c53cd96e5d today updates to the new polytope engine, which doesn't have the problem.
