### ISSUE TITLE
Ctrl-click by cubie not working for {3,3,3} 2

### ISSUE THREAD

**Issue by GoogleCodeExporter** [cutelyaware/magiccube4d#53]
```
This is similar to the grip problem I had with this puzzle (at first, you 
could never twist the puzzle!)  The issue is that the closest of the 
nicePointsToRotateToCenter is always the center of the cell.

The other simplexes work just fine.
```

Original issue reported on code.google.com by `roi...@gmail.com` on 19 Oct 2009 at 1:12

**Comment by cutelyaware** [comment]
Well it works, but... All the other cells end up inverted and therefore culled. I'm going to close this since the behavior does not appear to be different between simplexes of different edge lengths. Please reopen if something else is broken outside of the usability of simplexes given the current UI design.
